### ISSUE TITLE
Banner images should never show the cut image

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#30]
We need to make sure that the banner images never look like this when re-sized:
(image cutting off) 

<img width="571" alt="screen shot 2016-03-03 at 1 09 27 am" src="https://cloud.githubusercontent.com/assets/16873520/13486189/afdc608c-e0dc-11e5-8928-d332e6e21128.png">
<img width="294" alt="screen shot 2016-03-03 at 1 13 07 am" src="https://cloud.githubusercontent.com/assets/16873520/13486227/1c3993f8-e0dd-11e5-89ec-2961d239465b.png">
<img width="1118" alt="screen shot 2016-03-03 at 1 29 43 am" src="https://cloud.githubusercontent.com/assets/16873520/13486469/7192d060-e0df-11e5-83e8-912759a53fc1.png">

The objects in the banners should always appear like they are bleeding off the edge, like this example: 
https://www.paperlesspost.com/lp/wedding-invitations-timeline
(test it by resizing the window). 

In this example, images crop more off the sides, but never reveal the cut off along the bottom.

**Comment by nisho5** [comment]
Done

**Comment by laurakberglund** [comment]
None of these look fixed!

**Comment by laurakberglund** [comment]
I refreshed my cache, and now I can see how you updated these. They look better because they don't cut off at the bottom anymore, but now there is a problem where when the browser window resizes too much, you lose the whole image. I think it's ok for this initial launch, but when I send you the updated banner images with the spring menu boxes, I will be sure to send you multiples sizes for different browser widths, so the right and left sides come closer together as the browser resizes.

**Comment by nisho5** [comment]
Yes Perfect, I assume we will have to solve it that way.

**Comment by laurakberglund** [comment]
@nisho5 I just sent all the new images for the site. Please note, I saved the banners out two ways: one way where I split each banner into two sides, based on what we talked about in this issue. Hopefully we can make it work so the smaller the screen size, the more the two sides can overlap so we still see imagery even on an iPhone-sized screen. Thanks!
